### ISSUE TITLE
Esta tradução ainda está em desenvolvimento?

### ISSUE THREAD

**Issue by nbkhope** [franzejr/redux-in-portuguese#5]
Gostaria de saber do estado dessa tradução, pois tenho interesse de ajudar.

**Comment by franzejr** [comment]
Parei de traduzir, podemos continuar!

**Comment by franzejr** [comment]
@nbkhope, te coloquei como colaborador! Cada versão fazemos PR e cada um revisa, pode ser?

**Comment by nbkhope** [comment]
@franzejr obrigado. Além do PR, tem alguma outras regras que devo seguir? E a tradução, como deve ser?

**Comment by franzejr** [comment]
Em geral, tentar ser normal, mas também nem tanto. Dá uma olhada no que já está escrito pra tentar seguir o padrão. Não tem algo muito rigido não!
