### ISSUE TITLE
Documentos Pendentes

### ISSUE THREAD

**Issue by yanmagale** [franzejr/redux-in-portuguese#7]
Parabéns pela iniciativa, realmente precisamos de mais conteúdos técnicos em PT-BR

Queria saber quais arquivos de traduções que estão pendentes, gostaria de ajudar.

**Comment by codingleo** [comment]
@yanmagale Se quiser, pode judar com esse PR [aqui.](https://github.com/franzejr/redux-in-portuguese/pull/6) Comecei a traduzir, mas ainda falta bastante coisa.

Abraços!

**Comment by yanmagale** [comment]
Ok @leodsgn , irei traduzindo aos poucos e vou ir mandando para revisão.
